sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.10'
  - '0.12'
  - '4.0'
before_script:
  - npm install -g grunt-cli
after_success:
  # If build is successful, generate test coverage and push it to code climate
  - if [ "$TRAVIS_NODE_VERSION" = "0.12" ]; then ./codeclimate.sh; fi
