sudo: false
language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - iojs
before_script:
  - npm install -g grunt-cli
after_success:
  # If build is successful, generate test coverage and push it to code climate
- if [ "$TRAVIS_NODE_VERSION" = "0.12" ]; then ./codeclimate.sh; fi
