sudo: false
os:
 - linux
 - osx
language: node_js
node_js:
  - 'stable'
before_script:
  - npm install -g grunt-cli codecov
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - grunt ci
after_success:
  - 'codecov'
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
