sudo: false
language: node_js
addons:
  sauce_connect: true
node_js:
  - 'stable'
before_script:
  - npm install -g grunt-cli
script:
  - grunt ci
after_success:
  # If build is successful, generate test coverage and push it to code climate
  - if [ "$TRAVIS_NODE_VERSION" = "0.12" ]; then ./codeclimate.sh; fi
